from command import keyword_lib


_COMMAND_HELP = keyword_lib.COMMAND_HELP
_COMMAND_ACHIEVE = keyword_lib.COMMAND_ACHIEVE
_COMMAND_VIEW = keyword_lib.COMMAND_VIEW

_COMMAND_INDICATOR = keyword_lib.COMMAND_INDICATOR
_STRING_WRAPPER = keyword_lib.STRING_WRAPPER

_OR_SYNTAX = ' OR '

_USERNAME_PARAM_SYNTAX = _STRING_WRAPPER + '<username>' + _STRING_WRAPPER
_ACHIEVEMENT_NAME_PARAM_SYNTAX = _STRING_WRAPPER + '<achievement name>' + _STRING_WRAPPER

_HELP_COMMAND_START = _COMMAND_INDICATOR + _COMMAND_HELP
_ACHIEVE_COMMAND_START = _COMMAND_INDICATOR + _COMMAND_ACHIEVE
_VIEW_COMMAND_START = _COMMAND_INDICATOR + _COMMAND_VIEW

_ACHIEVE_COMMAND_REQ_SYNTAX = _ACHIEVE_COMMAND_START + ' ' + _USERNAME_PARAM_SYNTAX + ' ' + \
                              _ACHIEVEMENT_NAME_PARAM_SYNTAX
_VIEW_COMMAND_REQ_SYNTAX = _VIEW_COMMAND_START + ' ' + _USERNAME_PARAM_SYNTAX

_HELP_COMMAND_DESCRIPTION = "Lists commands and provides info for specific commands"
_ACHIEVE_COMMAND_DESCRIPTION = "Give a user a custom achievement"
_VIEW_COMMAND_DESCRIPTION = "View all the achievements that a user has or view a specific achievement"

_BRIEF_HEADER = "COMMANDS:"

_HELP_COMMAND_BRIEF = _COMMAND_HELP + ' ' + _HELP_COMMAND_DESCRIPTION
_ACHIEVE_COMMAND_BRIEF = _COMMAND_ACHIEVE + _ACHIEVE_COMMAND_DESCRIPTION
_VIEW_COMMAND_BRIEF = _COMMAND_VIEW + ' ' + _VIEW_COMMAND_DESCRIPTION

HELP_GENERAL_INFO = _HELP_COMMAND_BRIEF + '\n' + _ACHIEVE_COMMAND_BRIEF + '\n' + _VIEW_COMMAND_BRIEF

_HELP_COMMAND_SYNTAX = _HELP_COMMAND_START + _OR_SYNTAX + _COMMAND_HELP + ' <command>'
_ACHIEVE_COMMAND_SYNTAX = _ACHIEVE_COMMAND_REQ_SYNTAX + _OR_SYNTAX + \
                          _ACHIEVE_COMMAND_REQ_SYNTAX + ' ' + _STRING_WRAPPER + \
                          ' <achievement description>' + _STRING_WRAPPER
_VIEW_COMMAND_SYNTAX = _VIEW_COMMAND_REQ_SYNTAX + _OR_SYNTAX + \
                       _VIEW_COMMAND_REQ_SYNTAX + ' ' + _ACHIEVEMENT_NAME_PARAM_SYNTAX

_HELP_COMMAND_EXAMPLE_ONE = _HELP_COMMAND_START
_HELP_COMMAND_EXAMPLE_TWO = _HELP_COMMAND_START + ' ' + _STRING_WRAPPER + 'TheMightyMeercat' + _STRING_WRAPPER

# TODO: write rest of examples
